### ISSUE TITLE
Missing outdoor.yaml

### ISSUE THREAD

**Issue by eridgd** [uzh-rpg/rpg_public_dronet#11]
Two of the launch files refer to a bebop_driver config file `outdoor.yaml` that is not currently in the repo: 

https://github.com/uzh-rpg/rpg_public_dronet/blob/7c7fe7783b1d138776ee23279b669d240e13a040/drone_control/dronet/dronet_perception/launch/bebop_launch.launch#L6
https://github.com/uzh-rpg/rpg_public_dronet/blob/7c7fe7783b1d138776ee23279b669d240e13a040/drone_control/dronet/dronet_perception/launch/full_perception_launch.launch#L6

If I change this to `defaults.yaml` it launches, but I would be curious what outdoor-specific settings you are using.

**Comment by antonilo** [comment]
Thanks @eridgd for your comment! I added the file [outdoor.yaml](https://github.com/uzh-rpg/rpg_public_dronet/blob/master/drone_control/dronet/configs/outdoor.yaml). I will now update the documentation!

**Comment by antonilo** [comment]
Added file and updated docs

**Comment by eridgd** [comment]
Thanks!
