### ISSUE TITLE
test_classification

### ISSUE THREAD

**Issue by freaad** [uzh-rpg/rpg_public_dronet#14]
Written file C:\Users\donghok\Desktop\dronet_model\rpg_public_dronet-master2\dronet_model\constant_regression.json
Written file C:\Users\donghok\Desktop\dronet_model\rpg_public_dronet-master2\dronet_model\predicted_and_real_steerings.json
Average accuracy =  0.9530456852791879
Precision =  0.8951841359773371
Recall =  0.8951841359773371
F1-score =  0.8951841359773371
Written file C:\Users\donghok\Desktop\dronet_model\rpg_public_dronet-master2\dronet_model\test_classification.json
Average accuracy =  0.5253807106598984
Precision =  0.2348993288590604
Recall =  0.2348993288590604
F1-score =  0.31876138433515483
Written file C:\Users\donghok\Desktop\dronet_model\rpg_public_dronet-master2\dronet_model\random_classification.json
Written file C:\Users\donghok\Desktop\dronet_model\rpg_public_dronet-master2\dronet_model\predicted_and_real_labels.json

test classification is 0.5. What is the meaning. I mean real_steering looks fine.
The collision is 0.5?

**Comment by antonilo** [comment]
This is the result when using a random classifier for collision that, as you can expect, gives a 0.5 accuracy for binary classification!

**Comment by freaad** [comment]
This is not make sense. The Average accuracy is only 50% for binary classfication means it doesn't work well or do you mean it is just random classification.
