### ISSUE TITLE
How to use it in a simulator?

### ISSUE THREAD

**Issue by shivamsardana** [uzh-rpg/rpg_public_dronet#16]
Is there any way to use it on a simulator?

**Comment by eridgd** [comment]
Hi,

I hooked DroNet up to Gazebo + ROS for a class project, code is here https://github.com/eridgd/rotors-bebop. Here's a video of what it looks like trying to follow a simulated road environment: https://www.youtube.com/watch?v=Fr6A1GsdQUQ&t=15s

**Comment by antonilo** [comment]
wonderful work, thanks for sharing!
