### ISSUE TITLE
Integration with Drone

### ISSUE THREAD

**Issue by dharma-kc** [uzh-rpg/rpg_public_dronet#2]
Can you guys provide some documents for implementing these models into the real drone along with the flight controller hardware and firmware. That would be great. Thank you.

**Comment by antonilo** [comment]
Thanks for pointing that out. We will probably release the feature by next week!

**Comment by dronemaster13** [comment]
@antonilo Could you please update about the drone integration part? Thanks.

**Comment by antonilo** [comment]
We are now working on it. We will make it available by this week.

**Comment by eridgd** [comment]
I would also be very interested in the flight controller for the Bebop as I'm using the DroNet approach as part of a Deep RL course project. I really appreciate your publishing the code, thank you!

**Comment by antonilo** [comment]
Pull request #6 aims to add the dronet control part. Still it is not complete, but you can have a look at the code there if interested!

**Comment by antonilo** [comment]
Pull request merged. Will close this for now.
