### ISSUE TITLE
About 501 images from HMB_1 for validation experiment

### ISSUE THREAD

**Issue by Freddd13** [uzh-rpg/rpg_public_dronet#34]
Hi! I'm coming to the segment before the training.
According to your instruction, we need to split HMB_1 and 501 images of it are used for validation. So I wonder that how to select these '501 images'? Should I just select the last 501 images or use a script to randomly select them?

**Comment by antonilo** [comment]
Yes, random selection is what you need! They should be all forward-facing frames, though.
