### ISSUE TITLE
can not find ‘collision_dataset/testing/DSCN2571/sync_steering.txt'’

### ISSUE THREAD

**Issue by xiongdemao** [uzh-rpg/rpg_public_dronet#4]
(py3) n5@TitanX:~/test/dronet/rpg_public_dronet-master$ python evaluation.py --experiment_rootdir='./model' --weights_fname='model_weights.h5' --test_dir='/home/neu105/test/dronet/collision_dataset/testing' 
Using TensorFlow backend.
Traceback (most recent call last):
  File "evaluation.py", line 276, in <module>
    main(sys.argv)
  File "evaluation.py", line 272, in main
    _main()
  File "evaluation.py", line 180, in _main
    batch_size = FLAGS.batch_size)
  File "/home/n5/test/dronet/rpg_public_dronet-master/utils.py", line 34, in flow_from_directory
    follow_links=follow_links)
  File "/home/n5/test/dronet/rpg_public_dronet-master/utils.py", line 105, in __init__
    self._decode_experiment_dir(subpath)
  File "/home/n5/test/dronet/rpg_public_dronet-master/utils.py", line 131, in _decode_experiment_dir
    delimiter=',', skiprows=1)
  File "/home/n5/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/home/neu105/test/dronet/collision_dataset/testing/DSCN2571/sync_steering.txt'

**Comment by iqedgarmg** [comment]
Hi xiongdemao, did you find the solution of this issue?. I imagine that this issue is because some of the examples are used for the speed regulation and another for the steering angle control, but I cant find a solution to can run the script.

**Comment by Aaron9477** [comment]
> Hi xiongdemao, did you find the solution of this issue?. I imagine that this issue is because some of the examples are used for the speed regulation and another for the steering angle control, but I cant find a solution to can run the script.

Hi, guy! I have met this problems too. You can change the following two position from `OSError` to `IOError`. Maybe it will work.
https://github.com/uzh-rpg/rpg_public_dronet/blob/ac19c54bd6ac5a8fd1d220405ecf6f51af55d1f4/utils.py#L132
https://github.com/uzh-rpg/rpg_public_dronet/blob/ac19c54bd6ac5a8fd1d220405ecf6f51af55d1f4/utils.py#L137

Best wishes!
