### ISSUE TITLE
DroNet in the indoor environments

### ISSUE THREAD

**Issue by Yingxiu-Chang** [uzh-rpg/rpg_public_dronet#43]
@antonilo Hi Antonilo, 
I was reading your work, " Dronet: Learning to Fly by Driving", and trying to predict the steering and collision probabilities of indoor images. However, when I try to fly the UAV on AirSim, the UAV always stuck at the corner.

 In addition, I was using the following code to predict a single image. The model and the best weights I used was from https://github.com/uzh-rpg/rpg_public_dronet. In addition, I tested the single image from Himax_Dataset-master/test_2/frame_26.pgm from https://github.com/pulp-platform/pulp-dronet/tree/master/dataset. 

It's really good to test the outdoor images, but hard to get the correct results for indoor sceneries. 
I saw the video from https://www.youtube.com/watch?v=ow7aw9H4BcA&feature=youtu.be, which you tested the DroNet in your lab. Does it can steer at the corner of your lab corner? 
```
from PIL import Image
import utils
import numpy as np
import cv2


model = utils.jsonToModel("model/model_struct.json")
model.load_weights("model/best_weights.h5")
model.summary()


def central_image_crop(img, crop_width=150, crop_heigth=150):

    half_the_width = int(img.shape[1] / 2)
    img = img[img.shape[0] - crop_heigth: img.shape[0],
          half_the_width - int(crop_width / 2):
          half_the_width + int(crop_width / 2)]
    return img


def read_img():
    img = np.array(Image.open("./model/Himax_Dataset-master/test_2/frame_26.pgm"))  
    cv2.imshow('', img)
    cv2.waitKey(0)
    img_central = central_image_crop(img, 200, 200) 
    img_01 = np.asarray(img_central, dtype=np.float32) * np.float32(1.0/255.0) 
    img_3d = np.expand_dims(img_01, axis=0)  
    im_4d = img_3d[:, :, :, np.newaxis]    
    return im_4d



im = read_img()    
outs = model.predict([im])
steer, coll = outs[0][0], outs[1][0]
print("Steer angle= ", steer)
print("Collision prob= ", coll)
```

**Comment by antonilo** [comment]
hi @Hugh-Chang,

The performance indoor is inferior to the performance obtained outdoor. I guess the drone would have problems with sharp turns. However, it can avoid obstacles when navigating in a straight corridor.
