### ISSUE TITLE
HMB_3 experiment for testing

### ISSUE THREAD

**Issue by trqminh** [uzh-rpg/rpg_public_dronet#44]
Hi @antonilo,
I follow the readme to prepare the datasets. However, I cannot download the HMB_3 experiment since there is no seed for the torrent link (https://github.com/udacity/self-driving-car/blob/master/datasets/CH2/HMB_3.bag.tar.gz.torrent).

Do you know any other ways to access the data? Thank you for your consideration.

**Comment by antonilo** [comment]
I was able to download it a few days ago, could it be that you have download restrictions in your region? I invite you to double-check with the authors of the dataset, who detain ownership and copyright of the data!

**Comment by ZQY829** [comment]
I encountered the same problem, have you solved it
