### ISSUE TITLE
Evaluation results on the steering task

### ISSUE THREAD

**Issue by trqminh** [uzh-rpg/rpg_public_dronet#46]
Hi @antonilo,
I have run the evaluation with your best model. However, I got the result of 0.28 RMSE in the test set, which is different from your report in the paper (0.109  RMSE).

To be more specific, I wonder if I have tested in a test set different from yours. In fact, for the steering tasks, I download the test set as the HMB_3 release bag from this torrent (https://github.com/udacity/self-driving-car/tree/master/datasets/CH2#ch2_001). This test set has 5614 images and also includes the steering ground truths. Is it the same as the test set reported in the paper? Or maybe other problems or mismatches?

Thank you for your consideration.

![image](https://user-images.githubusercontent.com/30286786/121112901-5636f500-c83b-11eb-82f6-aa66a9dfce4c.png)

**Comment by antonilo** [comment]
hi @trqminh, I am not sure the result is correct since you get a negative EVA (which is worse than predicting a constant). Could it be that you have a problem with the ground truth? Can you check the predictions and see if they are random or normalized?

**Comment by trqminh** [comment]
Hi @antonilo,
Thank you for your answer. 
I don't really get the idea. Below are some of the values, min, max and mean of the two variables `real_steering` and `pred_steering` that are used to compute the RMSE and EVA.

About the `real_steering`, I take it from the csv file included in the test set (CH2_001). 

```
(Pdb) real_steerings
array([-0.3736651 , -0.06539629, -0.16073544, ...,  0.12909274,
       -0.04869618,  0.10666998], dtype=float32)
(Pdb) real_steerings.mean()
0.00048775805
(Pdb) real_steerings.min()
-0.39974692
(Pdb) real_steerings.max()
0.3991228
(Pdb) pred_steerings
array([-0.01978   ,  0.00637927, -0.04664509, ..., -0.01461499,
       -0.04642276, -0.01552933], dtype=float32)
(Pdb) pred_steerings.mean()
0.012114007
(Pdb) pred_steerings.min()
-0.84721583
(Pdb) pred_steerings.max()
0.86187893
```
![image](https://user-images.githubusercontent.com/30286786/121153481-4d144b00-c870-11eb-9544-534d3ae6adbb.png)

**Comment by antonilo** [comment]
Have you performed the data preprocessing steps as indicated in the README? I think that either the real or the predicted steering are not correctly normalized (they are 1 order of magnitude different).

**Comment by trqminh** [comment]
This is my silly mistake. Thank you for all your instant responses.

**Comment by Yingxiu-Chang** [comment]
Hi @trqminh,
I faced the problem that I cannot download the HMB_3 as testset since there is no seed of it. Do you know any other ways to download it ?
Yingxiu Chang
