### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by xiongdemao** [uzh-rpg/rpg_public_dronet#5]
(py3) neu105@TitanX:~/test/dronet/rpg_public_dronet-master$ python evaluation.py --experiment_rootdir='./model' --weights_fname='model_weights.h5' --test_dir='/home/neu105/test/dronet/collision_dataset/testing' 
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.5 locally
Found 6855 images belonging to 9 experiments.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:02:00.0
Total memory: 11.90GiB
Free memory: 11.75GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
Loaded model from ./model/model_weights.h5
Traceback (most recent call last):
  File "evaluation.py", line 276, in <module>
    main(sys.argv)
  File "evaluation.py", line 272, in main
    _main()
  File "evaluation.py", line 203, in _main
    model, test_generator, nb_batches, verbose = 1)
  File "/home/neu105/test/dronet/rpg_public_dronet-master/utils.py", line 254, in compute_predictions_and_gt
    generator_output = next(generator)
  File "/home/neu105/anaconda2/envs/py3/lib/python3.5/site-packages/keras/preprocessing/image.py", line 835, in __next__
    return self.next(*args, **kwargs)
  File "/home/neu105/test/dronet/rpg_public_dronet-master/utils.py", line 172, in next
    self.index_generator)
ValueError: too many values to unpack (expected 3)

**Comment by antonilo** [comment]
I guess you are not using the right keras version. Check that this is Keras 2.0.1! you could make it compatible to the newest version. If you are willing to, you are welcome to open a pull request!

**Comment by iqedgarmg** [comment]
You can remove your Keras version via the command: 

`pip uninstall keras`

and then reinstall the correct version (2.0.1) via: 

`pip install keras==2.0.1`
