### ISSUE TITLE
Evaluate testing data

### ISSUE THREAD

**Issue by iqedgarmg** [uzh-rpg/rpg_public_dronet#7]
Hi everyone! 

I have an issue when I try to evaluate the testing data set via the command line: 

`python evaluation.py --experiment_rootdir=./dronet --weights_fname='best_weights.h5' --test_dir='./testing'`

I get the following error:

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "evaluation.py", line 281, in <module>
>     main(sys.argv)
>   File "evaluation.py", line 277, in main
>     _main()
>   File "evaluation.py", line 183, in _main
>     batch_size = FLAGS.batch_size)
>   File "/home/edgar/rpg_public_dronet/utils.py", line 34, in flow_from_directory
>     follow_links=follow_links)
>   File "/home/edgar/rpg_public_dronet/utils.py", line 105, in __init__
>     self._decode_experiment_dir(subpath)
>   File "/home/edgar/rpg_public_dronet/utils.py", line 131, in _decode_experiment_dir
>     delimiter=',', skiprows=1)
>   File "/home/edgar/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 858, in loadtxt
>     fh = iter(open(fname, 'U'))
> IOError: [Errno 2] No such file or directory: './testing/DSCN2571/sync_steering.txt'

When I try to evaluate a dataset with only steering data parameters (with the steering dataset) it works fine but fails when the script tries to get the labels for collision probability:

> Using TensorFlow backend.
> Found 4401 images belonging to 1 experiments.
> ./dronet/best_weights.h5
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> Loaded model from ./dronet/best_weights.h5
> 137/137 [==============================] - 54s     
> EVA = 0.0
> RMSE = 0.0794238299131
> Written file ./dronet/constant_regression.json
> EVA = -1.00365029169
> RMSE = 0.112437359102
> Written file ./dronet/random_regression.json
> EVA = 0.10682195425
> RMSE = 0.0805458426476
> Written file ./dronet/test_regression.json
> Written file ./dronet/predicted_and_real_steerings.json
> /home/edgar/.local/lib/python2.7/site-packages/numpy/lib/function_base.py:1110: RuntimeWarning: Mean of empty slice.
>   avg = a.mean(axis)
> /home/edgar/.local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> ('Average accuracy = ', nan)
> ('Precision = ', 0.0)
> ('Recall = ', 0.0)
> ('F1-score = ', 0.0)
> Traceback (most recent call last):
>   File "evaluation.py", line 281, in <module>
>     main(sys.argv)
>   File "evaluation.py", line 277, in main
>     _main()
>   File "evaluation.py", line 261, in _main
>     evaluate_classification(pred_prob, pred, real_labels, abs_fname)
>   File "evaluation.py", line 163, in evaluate_classification
>     dictionary = {"ave_accuracy": ave_accuracy.tolist(), "precision": precision.tolist(),
> AttributeError: 'float' object has no attribute 'tolist'

I think that it is because one part of the dataset is for steering angle prediction (udacity-dataset with sync_steering.txt) and another for collision estimation (collision data with labels.txt). Nevertheless, I didn't find a solution for testing both.  

I am doing something wrong?, Do I need to define an special configuration for testing both?.

Thanks in advance for your response.

Greetings!

**Comment by antonilo** [comment]
Hi @iqedgarmg!
Unfortunately I am not able to reproduce your error. There should be a try except block [here](https://github.com/uzh-rpg/rpg_public_dronet/blob/master/utils.py#L129) that is supposed to load collision labels in a collision directory. This allows you to load either steerings or collisions, depending by what is available.
Could you double check that this line was not commented?

**Comment by iqedgarmg** [comment]
Hi antonilo thanks for your answer! 

For some unknown reason that line was commented. Now the script runs correctly. 

Thanks a lot!
