### ISSUE TITLE
Unknown CMake command "quad_cmake_setup"

### ISSUE THREAD

**Issue by eridgd** [uzh-rpg/rpg_public_dronet#8]
Thanks so much for publishing the control code, it's saved me quite a bit of time and I appreciate how straightforward it is.

I encountered this error when building dronet_control:

`CMake Error at /home/eridgd/bebop_ws/src/dronet/dronet_control/CMakeLists.txt:6 (quad_cmake_setup):
  Unknown CMake command "quad_cmake_setup"`

Which seems to be due to a missing non-standard dependency. If I comment out this line in CMakeLists.txt it does seem to then build. Can I safely ignore this?

**Comment by antonilo** [comment]
Yes definitely, thanks @eridgd for pointing that out. Should be now corrected in master.
